---
- name: Setup Kubernetes prerequisites with CRI-O
  hosts: all
  become: yes

  vars:
    kubernetes_version: "v1.33"
    crio_version: "v1.31"

  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: Load CRI-O kernel modules config
      copy:
        dest: /etc/modules-load.d/crio.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Configure sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Set IP forwarding immediately
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Also persist IP forwarding in /etc/sysctl.d/k8s.conf
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1

    - name: Apply all sysctl settings
      command: sysctl --system

    - name: Install required dependencies
      apt:
        name:
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    - name: Add Kubernetes apt key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key |
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repo
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /

    - name: Add CRI-O apt key
      shell: |
        curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/Release.key |
        gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/cri-o-apt-keyring.gpg

    - name: Add CRI-O apt repo
      copy:
        dest: /etc/apt/sources.list.d/cri-o.list
        content: |
          deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/ /

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, kubectl, and cri-o
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - cri-o
        state: present

    - name: Hold Kubernetes packages to prevent updates
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no
        force: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start CRI-O
      systemd:
        name: crio
        enabled: yes
        state: started
