apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-fe
  labels:
    app: sip-frontend
spec:
  replicas: 1 # You can increase this for higher availability
  selector:
    matchLabels:
      app: sip-frontend
  template:
    metadata:
      labels:
        app: sip-frontend
    spec:
      containers:
      - name: sip-frontend
        image: alamshkh1/bluevault-sip-fe:v4 # Replace with your Docker Hub username and tag
        ports:
        - containerPort: 80 # Nginx listens on port 80

---

apiVersion: v1
kind: Service
metadata:
  name: sip-frontend-service
  labels:
    app: sip-frontend
spec:
  selector:
    app: sip-frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 80 # The port the container is listening on (Nginx)
      nodePort: 30082 # Optional: A specific port on the node to expose the service. Must be in range 30000-32767.
  type: NodePort # Exposes the service on a port on each Node's IP. For external access.
  # If you are on a cloud provider (EKS, GKE, AKS), you might prefer type: LoadBalancer
  # type: LoadBalancer
